..\..\..\..\..\adjirrig.exe Harvest.mgt 100 90 80 70 60 50 40  30 20 10 0 < optimal.dat

REM for /D %%G in ("V100F*") do rd /s /q "%%~G"
for /D %%G in ("V90F*") do rd /s /q "%%~G"
for /D %%G in ("V80F*") do rd /s /q "%%~G"
for /D %%G in ("V70F*") do rd /s /q "%%~G"
for /D %%G in ("V60F*") do rd /s /q "%%~G"
for /D %%G in ("V50F*") do rd /s /q "%%~G"
for /D %%G in ("V40F*") do rd /s /q "%%~G"
for /D %%G in ("V30F*") do rd /s /q "%%~G"
for /D %%G in ("V20F*") do rd /s /q "%%~G"
for /D %%G in ("V10F*") do rd /s /q "%%~G"
for /D %%G in ("V0F*") do rd /s /q "%%~G"

REM for /D %%G in ("*F100G*") do rd /s /q "%%~G"
for /D %%G in ("*F90G*") do rd /s /q "%%~G"
for /D %%G in ("*F80G*") do rd /s /q "%%~G"
for /D %%G in ("*F70G*") do rd /s /q "%%~G"
for /D %%G in ("*F60G*") do rd /s /q "%%~G"
for /D %%G in ("*F50G*") do rd /s /q "%%~G"
for /D %%G in ("*F40G*") do rd /s /q "%%~G"
for /D %%G in ("*F30G*") do rd /s /q "%%~G"
for /D %%G in ("*F20G*") do rd /s /q "%%~G"
for /D %%G in ("*F10G*") do rd /s /q "%%~G"
for /D %%G in ("*F0G*") do rd /s /q "%%~G"

REM for /D %%G in ("*G100") do rd /s /q "%%~G"
REM for /D %%G in ("*G90") do rd /s /q "%%~G"
REM for /D %%G in ("*G80") do rd /s /q "%%~G"
REM for /D %%G in ("*G70") do rd /s /q "%%~G"
REM for /D %%G in ("*G60") do rd /s /q "%%~G"
REM for /D %%G in ("*G50") do rd /s /q "%%~G"
REM for /D %%G in ("*G40") do rd /s /q "%%~G"
REM for /D %%G in ("*G30") do rd /s /q "%%~G"
REM for /D %%G in ("*G20") do rd /s /q "%%~G"
REM for /D %%G in ("*G10") do rd /s /q "%%~G"
REM for /D %%G in ("*G0") do rd /s /q "%%~G"